websites_wallet/wallet/urls.py
from django.conf.urls import url

from . import views

app_name = 'wallet'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'register/$', views.register, name='register'),
    url(r'login/$', views.user_login, name='login'),
    url(r'logout/$', views.user_logout, name='logout'),
    url(r'^(?P<payment_amount>[0-9]+)/(?P<item_id>[0-9]+)/$', views.payment, name='payment'),
    url(r'coinsuccess/$', views.coinsuccess, name='coinsuccess'),
    url(r'coinsuccess2/$', views.coinsuccess2, name='coinsuccess2'),
    url(r'convertingcoinsbacktomoney/(?P<coinnum>[0-9]+)/(?P<coinpk>[0-9]+)/$', views.convertingcoinsbacktomoney, name='convertingcoinsbacktomoney'),
    url(r'^coindestroysuccess/(?P<num_of_coins>[0-9]+)/(?P<coinpk>[0-9]+)/$', views.coindestroysuccess, name='coindestroysuccess'),
    url(r'^coindestroysuccess2/(?P<num_of_coins>[0-9]+)/$', views.coindestroysuccess2, name='coindestroysuccess2'),
	url(r'create_coins/$', views.create_coins, name='create_coins'),
    url(r'ws_coin_list/$', views.ws_coin_list, name='ws_coin_list'),
]

websites_wallet/websites_wallet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^wallet/', include('wallet.urls')),
    url(r'^wallet/admin/', admin.site.urls),
]

websites_wallet/wallet/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# https://docs.djangoproject.com/en/1.9/topics/db/examples/many_to_one/
# https://docs.djangoproject.com/en/dev/ref/models/fields/#choices
@python_2_unicode_compatible  # only if you need to support Python 2
class Coins(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	value_of_coin = models.IntegerField(choices=settings.COIN_VALUE_CHOICES)
	serialised_code_rnd_tau_gam_R_att = models.CharField(max_length=500, )
	expirydate = models.IntegerField()

	def __str__(self):
		return ' '.join([
			str(self.user.username),
			str(self.value_of_coin)
		])


@python_2_unicode_compatible  # only if you need to support Python 2
class PaymentSession(models.Model):
	sessionID = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	amount = models.IntegerField()

	def __str__(self):
		return self.user.username + " " + str(self.amount)

websites_wallet/wallet/forms.py
from django import forms 
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.template import RequestContext

# https://docs.djangoproject.com/en/1.9/ref/validators/
# https://docs.djangoproject.com/en/dev/ref/forms/fields/#choicefield

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username',)

class GetCoinForm(forms.Form):
    # http://tutorial.djangogirls.org/en/django_forms/
    # https://docs.djangoproject.com/en/1.9/topics/forms/modelforms/
    coinnum = forms.ChoiceField(label='Number of coins wanted:', choices=settings.COIN_VALUE_CHOICES)

websites_wallet/wallet/views.py
from django import forms
from django.conf import settings
from django.contrib import auth
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext

from wallet.forms import GetCoinForm, RegisterForm
from wallet.models import PaymentSession, Coins

import BLcred, blshim

import time, requests, datetime

fo = open("timings_wallet.csv", "a", 0)

def user_login(request):
    # http://stackoverflow.com/questions/16750464/django-redirect-after-login-not-working-next-not-posting
    # Obtain the context for the user's request.
    context = RequestContext(request)

    next = ""
    if request.GET:  
        next = request.GET['next']

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                if next == "":
                    return HttpResponseRedirect('/wallet/')
                else:
                    return HttpResponseRedirect(next)
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return render(request, 'wallet/login.html', {'next':next, 'error_message': "Invalid login details supplied."})

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        # http://stackoverflow.com/questions/21498682/django-csrf-verification-failed-request-aborted-csrf-cookie-not-set
        return render(request, 'wallet/login.html', {'next':next})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/wallet/')


def register(request):
	# https://docs.djangoproject.com/en/1.9/topics/forms/
    # http://www.tangowithdjango.com/book/chapters/login.html#creating-a-user-registration-view-and-template
	# http://stackoverflow.com/questions/8917185/in-django-when-i-call-user-objects-create-userusername-email-password-why

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
			# process the data in form.cleaned_data as required

            new_user = User.objects.create_user(
                username=form.cleaned_data['username'],  
                password=form.cleaned_data['password1'])
            new_user.save()

            if new_user is not None:
                login(request, new_user)

            # redirect to a new URL:
            return HttpResponseRedirect('/wallet/')
            
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render(request, 'wallet/register.html', {'form': form})


@login_required
def homepage(request):
    # http://stackoverflow.com/questions/17754295/can-i-have-a-django-form-without-model
    if request.method == 'POST':
        form = GetCoinForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            context = {
                'coinnum': cd.get('coinnum'),
                'BANK_URL': settings.BANK_URL
            }

            return render(request, 'wallet/gettingcoins.html', context)
    else:
        form = GetCoinForm()

    users_coins = Coins.objects.filter(user=request.user)
    context = {
        'form': form,
        'users_coins': users_coins
    }
    return render(request, 'wallet/homepage.html', context)


#########################################################################################
# User - coin creation
@login_required
def coinsuccess(request):
    num_of_coins, sessionid = blshim.deserialise(request.GET.get('entry'))

    valid = create_coins(request, num_of_coins, sessionid, request.user)

    if valid: 
        return render(request, 'wallet/coinsuccess.html', {'num_of_coins': num_of_coins})
    else:
        return HttpResponse("pi proof failed")


@login_required
def coinsuccess2(request):
    # breaks out of iframe
    return render(request, 'wallet/coinsuccess2.html')


def create_coins(request, coinnum, sessionid, user):
    # Do all of the crypto and ws interaction with the bank to create the coins
    # http://www.saltycrane.com/blog/2008/06/how-to-get-current-date-and-time-in/
    now = datetime.datetime.now() 
    expirydate = now.year + 2

    if user.username == "expiredspender":
        expirydate = now.year - 2

    start = time.time()
    LT_user_state, user_commit = BLcred.BL_user_setup(blshim.params, [coinnum, expirydate])
    fo.write("BLcred.BL_user_setup, " + str(time.time() - start) + "\n")

    (C, ) = user_commit

    start = time.time()
    pi_proof_values = blshim.pi_proof_wallet(C, LT_user_state.R, coinnum, expirydate)
    fo.write("blshim.pi_proof_wallet, " + str(time.time() - start) + "\n")    
    
    s_entry = blshim.serialise((pi_proof_values, user_commit, sessionid, coinnum, expirydate))

    start = time.time()
    r = requests.get(settings.BANK_URL + '/ws_preparation_validation_1/?serialised_entry=%s' %(s_entry))
    fo.write("bank/ws_preparation_validation_1, " + str(time.time() - start) + "\n")
    c = r.content

    (valid, results) = blshim.deserialise(c)

    if valid:
        rnd, aap = results

        start = time.time()
        BLcred.BL_user_preparation(LT_user_state, rnd)
        fo.write("BLcred.BL_user_preparation, " + str(time.time() - start) + "\n")   

        start = time.time()
        msg_to_issuer_e = epsilon = BLcred.BL_user_validation(LT_user_state, (blshim.y, ), aap)
        fo.write("BLcred.BL_user_validation, " + str(time.time() - start) + "\n")  

        # new webservice here
        # sending e
        s_entry = blshim.serialise((msg_to_issuer_e, user_commit, sessionid))
        
        start = time.time()
        r = requests.get(settings.BANK_URL + '/ws_validation_2/?serialised_entry=%s' %(s_entry))
        fo.write("bank/ws_validation_2, " + str(time.time() - start) + "\n")
        c = r.content

        msg_to_user_crcprp = blshim.deserialise(c)

        start = time.time()
        signature = BLcred.BL_user_validation2(LT_user_state, msg_to_user_crcprp)
        fo.write("BLcred.BL_user_validation2, " + str(time.time() - start) + "\n")  

        ##VALIDATION THAT THE COIN IS VALID
        start = time.time()
        b = BLcred.BL_check_signature(blshim.params, (blshim.y, ), signature)
        fo.write("BLcred.BL_check_signature, " + str(time.time() - start) + "\n")

        # Saving the coin into the DB
        # signature and coins are different - mu
        # serialising the stuff to save in the db
        (m, LT_user_state.zet, LT_user_state.zet1, LT_user_state.zet2, om, omp, ro, ro1p, ro2p, mu) = signature

        coin = (m, LT_user_state.zet, LT_user_state.zet1, LT_user_state.zet2, om, omp, ro, ro1p, ro2p)

        serialised_code_rnd_tau_gam_R_att = blshim.serialise((coin, rnd, LT_user_state.tau, LT_user_state.gam, LT_user_state.R, LT_user_state.attributes))

        c = Coins(user=user, value_of_coin=coinnum, serialised_code_rnd_tau_gam_R_att=serialised_code_rnd_tau_gam_R_att, expirydate=expirydate)
        c.save()

    return valid 


#########################################################################################
# Spending coins
@login_required
def payment(request, payment_amount, item_id):
    sessionid = request.session._session_key

    # if sessionid exists already in the db, delete it
    try:
        test = PaymentSession.objects.get(sessionID=sessionid)
        test.delete()
    except PaymentSession.DoesNotExist:
        pass

    # create a session db to record information about the sale for the validation later
    PaymentSession(sessionID=sessionid, user=request.user, amount=payment_amount).save()

    context = {
        'payment_amount':payment_amount, 
        'item_id':item_id,
        'serialised_entry': blshim.serialise((item_id, sessionid)),
        'MERCHANT_URL': settings.MERCHANT_URL
    }
    return render(request, 'wallet/payment.html', context)


def ws_coin_list(request):
    # generates list of coins to send to merchant
    # together with the spending and reveal protocols attributes
    error = False
    error_reason = ""
    msg_to_merchant_epmupcoin = [""]
    serialised_entry = request.GET.get('entry')
    desc, sessionid, im = blshim.deserialise(serialised_entry)

    # user is extracted from the session information
    ps = PaymentSession.objects.get(sessionID=sessionid)
    amount = ps.amount
    user = ps.user

websites_wallet/wallet/templates/wallet/base.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/wallet.css' %}">
    </head>
    <body>

        <div class="page-header">
            <h1><a href="{% url 'wallet:homepage' %}">Wallet</a></h1>

            {% if user.is_authenticated %}
            <h6><a href="{% url 'wallet:logout' %}">Logout</a></h6>
            {% endif %}
        </div>
        
        <div id="block">
            {% block content %}
            {% endblock %}
        </div>

    </body>
</html>

websites_wallet/wallet/templates/wallet/coindestroysuccess.html
<script>
	if (top.location!= self.location) {
	   top.location = "{% url 'wallet:coindestroysuccess2' num_of_coins %}";
	}
</script>

websites_wallet/wallet/templates/wallet/coindestroysuccess2.html
{% extends 'wallet/base.html' %}
{% block content %}

	<p><b>{{ num_of_coins }}</b> coins converted back into money successfully</p>

{% endblock %}

websites_wallet/wallet/templates/wallet/coinsuccess.html
<script>
	if (top.location!= self.location) {
	   top.location = "{% url 'wallet:coinsuccess2' %}";	   
	}
</script>

websites_wallet/wallet/templates/wallet/coinsuccess2.html
{% extends 'wallet/base.html' %}
{% block content %}

	<p><b>{{ num_of_coins }}<b> coins created successfully</p>

{% endblock %}

websites_wallet/wallet/templates/wallet/convertingcoinsbacktomoney.html
{% extends 'wallet/base.html' %}
{% block content %}
<div id="convertingcoinsbackintomoney">

	<p>Number of coins to be turned back into money: <b>{{ coinnum }}</b></p>

	<iframe src="{{ BANK_URL }}/coindestroy/{{ coinnum }}/{{ coinpk }}" width="400" height="300"></iframe>

	{# {% url 'wallet:coindestroysuccess2' num_of_coins %} #}

</div>
{% endblock %}

websites_wallet/wallet/templates/wallet/gettingcoins.html
{% extends 'wallet/base.html' %}
{% block content %}

	<p>Number of coins to be created: <b>{{ coinnum }}</b></p>

	<iframe src="{{ BANK_URL }}/coincreation/{{ coinnum }}" width="700" height="700"></iframe>

{% endblock %}

websites_wallet/wallet/templates/wallet/homepage.html
{% extends 'wallet/base.html' %}
{% block content %}
<div id="homepage">    

    <h2>Hi {{ user.username }}</h2>

    {% load bootstrap3 %}

    <form action="{% url 'wallet:homepage' %}" method="post" class="form-inline">

        {% csrf_token %}

        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success">
                Submit
            </button>
        {% endbuttons %}

    </form>


    {% if users_coins %}

    <h3>List of coins:</h3>
        <table>
        	<tr>
        		<th>Coin value:</th>
        	</tr>
        	
    		{% for coin in users_coins %}
    		<tr>
    			<td>{{ coin.value_of_coin }}</td>
    			<td><a href="{% url 'wallet:convertingcoinsbacktomoney' coin.value_of_coin coin.pk %}"><button class="btn btn-success btn-large" type="button">Turn back into money</button></a></td>
    		</tr>
    	    {% endfor %}
        </table>
    {% else %}

        
        <h3>Currently you have no coins. Create some above.</h3>
    {% endif %}

</div>
{% endblock %}

websites_wallet/wallet/templates/wallet/login.html
{% extends 'wallet/base.html' %}
{% block content %}
<div id="login" class="container">
	<div class="well well-small">

		<h2>Log in</h2>

		<div id="error_message">
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		</div>

		{% if next %}
		<form action="/wallet/login/?next={{next}}" method="post" >
		{%else%}
		<form action="{% url 'wallet:login' %}" id="login_form" method="post">
		{% endif %}
		{% csrf_token %}
			<div class="form-group">
                <div class="input-group">
				    <div class="input-group-addon"><i class="glyphicon glyphicon-user"></i></div>
				    <input type="text" name="username" class="form-control" placeholder="username" required="required"  value="" size="50">
			    </div>
			    <div class="input-group">
			    	<div class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></div>
			    	<input type="password" class="form-control" name="password" placeholder="password" required="required" value="" size="50">
			    </div>
			</div>
		    <div class="form-group">
		    	<input type="submit" class="btn btn-success btn-large btn-block" value="Log in" />
		    </div>
		</form>

		<a href="{% url 'wallet:register' %}">Register Here</a>

	</div>
</div>

{% endblock %}

websites_wallet/wallet/templates/wallet/payment.html
{% extends 'wallet/base.html' %}
{% block content %}
<div id="payment">

	<p>Do you want to pay <b>{{ user_getting_money.username }}</b><br>
		Amount: <b>{{ payment_amount }}</b> coins?</p>

	<a href="{{ MERCHANT_URL }}/success/?entry={{ serialised_entry }}"><button type="button">YES</button></a> 
	<a href="{{ MERCHANT_URL }}/{{ item_id }}/" target="_parent"><button type="button">NO - take me back</button></a> 

</div>
{% endblock %}

websites_wallet/wallet/templates/wallet/register.html
{% extends 'wallet/base.html' %}
{% block content %}
<div id="register" class="container">
	<div class="well well-small">

	<h2>Sign up</h2>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	{% load bootstrap3 %}

	<form action="{% url 'wallet:register' %}" method="post">
	{% csrf_token %}
	  
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success">
                Create Account
            </button>
		{% endbuttons %}
	</form>

	</div>
</div>

{% endblock %}