websites_bank/bank/urls.py
from django.conf.urls import url

from . import views

app_name = 'bank'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^coincreation/(?P<num_of_coins>[0-9]+)/$', views.coincreation, name='coincreation'),
    url(r'^confirmcoincreation/(?P<num_of_coins>[0-9]+)/$', views.confirmcoincreation, name='confirmcoincreation'),
    url(r'^coindestroy/(?P<num_of_coins>[0-9]+)/(?P<coinpk>[0-9]+)/$', views.coindestroy, name='coindestroy'),
    url(r'^coindestroysuccess/(?P<num_of_coins>[0-9]+)/(?P<coinpk>[0-9]+)/$', views.coindestroysuccess, name='coindestroysuccess'),
    url(r'ws_preparation_validation_1/$', views.ws_preparation_validation_1, name='ws_preparation_validation_1'),
    url(r'ws_validation_2/$', views.ws_validation_2, name='ws_validation_2'),
    url(r'ws_spend_reveal/$', views.ws_spend_reveal, name='ws_spend_reveal'),
]

websites_bank/websites_bank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bank/', include('bank.urls')),
    url(r'^bank/admin/', admin.site.urls),
]

websites_bank/bank/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# http://stackoverflow.com/questions/6085025/django-user-profile
# http://stackoverflow.com/questions/26306424/cant-login-a-just-created-user-in-a-django-test
# http://stackoverflow.com/questions/34578193/minvaluevalidator-not-working-on-decimalfield-in-django
@python_2_unicode_compatible  # only if you need to support Python 2
class UserProfile(models.Model):  
    user = models.OneToOneField(User, related_name='profile')
    balance = models.IntegerField(
        default=20, 
        validators=[validators.MinValueValidator(1)]
        )

    def __str__(self):
        return ' '.join([
			str(self.user.username),
    		str(self.user.first_name),
    		str(self.user.last_name),
    		str(self.user.email),
    		str(self.balance)
		])


@python_2_unicode_compatible  # only if you need to support Python 2
class CoinValidation(models.Model):
    commitment = models.TextField()
    jsonstring = models.TextField()
    sessionID = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    num_of_coins = models.IntegerField()

    def __str__(self):
        return self.commitment


@python_2_unicode_compatible  # only if you need to support Python 2
class DoubleSpendingz1Touser(models.Model):
    z1 = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value_of_coin = models.IntegerField()
    expirydate = models.IntegerField()

    def __str__(self):
        return self.user.username + " " + self.z1 


@python_2_unicode_compatible  # only if you need to support Python 2
class DoubleSpendingCoinHistory(models.Model):
    coin = models.TextField()

    # epsilonp, mup
    serialised_entry = models.TextField()

    def __str__(self):
        return self.coin + "     " + self.serialised_entry


@python_2_unicode_compatible  # only if you need to support Python 2
class UsersWhoHaveDoubleSpent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)
    coin = models.TextField()

    # epsilonp, mup
    serialised_entry = models.TextField()

    def __str__(self):
        return ' '.join([
            self.user.username,
            str(self.time),
            self.coin
        ])

websites_bank/bank/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    # http://stackoverflow.com/questions/16562529/django-1-5-usercreationform-custom-auth-model
    # http://jessenoller.com/blog/2011/12/19/quick-example-of-extending-usercreationform-in-django
    # https://github.com/django/django/blob/master/django/contrib/auth/forms.py

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

websites_bank/bank/views.py
from django import forms
from django.conf import settings
from django.contrib import auth
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render
from django.template import RequestContext, loader

from bank.forms import RegisterForm
from bank.models import UsersWhoHaveDoubleSpent, DoubleSpendingCoinHistory, DoubleSpendingz1Touser, CoinValidation, UserProfile

import blshim, BLcred

import time, datetime

fo = open("timings_bank.csv", "a", 0)

def user_login(request):
    # http://stackoverflow.com/questions/16750464/django-redirect-after-login-not-working-next-not-posting
    # Obtain the context for the user's request.
    context = RequestContext(request)
    next = ""
    if request.GET:  
        next = request.GET['next']

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)

                if next == "":
                    return HttpResponseRedirect('/bank/')
                else:
                    return HttpResponseRedirect(next)

            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        # http://stackoverflow.com/questions/21498682/django-csrf-verification-failed-request-aborted-csrf-cookie-not-set
        return render(request, 'bank/login.html', {'next': next})


# http://www.tangowithdjango.com/book/chapters/login.html
# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/bank/')


def register(request):
	# https://docs.djangoproject.com/en/1.9/topics/forms/
    # http://www.tangowithdjango.com/book/chapters/login.html#creating-a-user-registration-view-and-template
	# http://stackoverflow.com/questions/8917185/in-django-when-i-call-user-objects-create-userusername-email-password-why

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
			# process the data in form.cleaned_data as required
            new_user = User.objects.create_user(
                username=form.cleaned_data['username'], 
                email=form.cleaned_data['email'], 
                first_name=form.cleaned_data['first_name'], 
                last_name=form.cleaned_data['last_name'], 
                password=form.cleaned_data['password1'])
            new_user.save()

            profile = UserProfile(user_id=new_user.id)
            profile.save()

            if new_user is not None:
                login(request, new_user)

            # redirect to a new URL:
            return HttpResponseRedirect('/bank/')
            
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render(request, 'bank/register.html', {'form': form})


@login_required
def homepage(request):
    return render(request, 'bank/homepage.html')

#########################################################################################
# User - coin creation
@login_required
def coincreation(request, num_of_coins):
    return render(request, 'bank/coincreation.html', {'num_of_coins': num_of_coins})


@login_required
def confirmcoincreation(request, num_of_coins):
    # User has confirmed wanting to make the coins, updates bank balance
    # and starts the crypto process
    new_balance = int(request.user.profile.balance) - int(num_of_coins)

    if (new_balance) < 0:
        return HttpResponse("Bank: Cannot create coins - insufficient funds")
    else:
        # We need to track a number of variables across a number of webservice calls
        # so capture these in a session db
        sessionid = request.session._session_key

        # Remove any old entries that might have been created by defects
        CoinValidation.objects.filter(sessionID=sessionid).delete()
    
        CoinValidation(sessionID=sessionid, user=request.user, num_of_coins=num_of_coins, commitment="", jsonstring="").save()
        
        entry = blshim.serialise((int(num_of_coins), sessionid))
        return HttpResponseRedirect(settings.WALLET_URL + '/coinsuccess/?entry=%s' %(entry))


#########################################################################################
# Coin creation - webservice call
def ws_preparation_validation_1(request):
    # PREPARATION STAGE - BL_issuer_preparation
    serialised_entry = request.GET.get('serialised_entry')
    pi_proof_values, real_C, sessionid, value_of_coin, expirydate = blshim.deserialise(serialised_entry)

    # Standard non-interactive proof of knowledge - pi proof
    # validation that the coin value and expiry date have been set correctly by the wallet
    start = time.time()
    pi_proof_bank = blshim.pi_proof_bank(pi_proof_values)
    fo.write("blshim.pi_proof_bank, " + str(time.time() - start) + "\n")

    if pi_proof_bank:
        start = time.time()
        LT_issuer_state = blshim.create_issuer_state()
        fo.write("blshim.create_issuer_state, " + str(time.time() - start) + "\n")

        start = time.time()
        msg_to_user_rnd = BLcred.BL_issuer_preparation(LT_issuer_state, real_C)
        fo.write("BLcred.BL_issuer_preparation, " + str(time.time() - start) + "\n")
        
        # VALIDATION STAGE 1 - BL_issuer_validation
        start = time.time()
        msg_to_user_aap = BLcred.BL_issuer_validation(LT_issuer_state)
        fo.write("BLcred.BL_issuer_validation, " + str(time.time() - start) + "\n")
        
        results = msg_to_user_rnd, msg_to_user_aap

        # can't easily use sessions - browsers
        serialised_C = blshim.serialise(real_C)
        js_cpu = blshim.serialise((LT_issuer_state.cp, LT_issuer_state.u, LT_issuer_state.r1p, LT_issuer_state.r2p))

        session_details = CoinValidation.objects.get(sessionID=sessionid)
        session_details.commitment=serialised_C
        session_details.jsonstring=js_cpu
        session_details.save()

        DoubleSpendingz1Touser(z1=blshim.serialise(LT_issuer_state.z1), user=session_details.user, expirydate=expirydate, value_of_coin=value_of_coin).save()

        return HttpResponse(blshim.serialise((True, results)))
    else:
        return HttpResponse(blshim.serialise((False, "problems with pi proof")))


def ws_validation_2(request):
    serialised_entry = request.GET.get('serialised_entry')
    real_e, real_c, sessionid = blshim.deserialise(serialised_entry)

    serialised_C = blshim.serialise(real_c)

    db = CoinValidation.objects.get(sessionID=sessionid)

    # need to deduct the money from the user's account
    # and confirm the number of coins requested is the same as that approved earlier 
    start = time.time()
    LT_issuer_state =  blshim.create_issuer_state()
    fo.write("blshim.create_issuer_state, " + str(time.time() - start) + "\n")

    LT_issuer_state.cp, LT_issuer_state.u, LT_issuer_state.r1p, LT_issuer_state.r2p = blshim.deserialise(db.jsonstring)

    start = time.time()
    msg_to_user_crcprp = BLcred.BL_issuer_validation_2(LT_issuer_state, real_e)
    fo.write("BLcred.BL_issuer_validation_2, " + str(time.time() - start) + "\n")

    # updating user's balance
    u = db.user
    u.profile.balance = int(u.profile.balance) - db.num_of_coins
    u.profile.save()

    # finished with "session" so now delete it
    db.delete()

    return HttpResponse(blshim.serialise(msg_to_user_crcprp))


#########################################################################################
# Coin spending
def ws_spend_reveal(request):
    valid = True
    error_reason = ""
    list_of_coins_to_put_in_db = []

    serialised_entry = request.GET.get('entry')
    list_of_msgs, desc, im, amount = blshim.deserialise(serialised_entry)

    #serialiser converts lists to tuples by default
    list_of_msgs = list(list_of_msgs)

    for coin_with_reveals in list_of_msgs:
        msg_to_merchant_epmupcoin, amount_rev_values, expiry_rev_values, value_of_coin, expirydate = coin_with_reveals

        start = time.time()

websites_bank/bank/templates/bank/base.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/bank.css' %}">
    </head>
    <body>

        <div class="page-header">
            <h1><a href="{% url 'bank:homepage' %}">Bank</a></h1>

        {% if user.is_authenticated %}
            <h6><a href="{% url 'bank:logout' %}">Logout</a></h6>
            {% endif %}
        </div>
        
        <div id="block">
            {% block content %}
            {% endblock %}
        </div>

    </body>
</html>

websites_bank/bank/templates/bank/coincreation.html
{% extends 'bank/base.html' %}
{% block content %}
<div id="coincreation" class="container">

	<h3>Confirmation of coin creation</h3>

	<p><b>{{ num_of_coins }}</b> coins to be made</p>

	<a href="{% url 'bank:confirmcoincreation' num_of_coins %}"><button class="btn btn-primary btn-large btn-block" type="button">YES</button></a>

</div>
{% endblock %}

websites_bank/bank/templates/bank/coindestroy.html
{% extends 'bank/base.html' %}
{% block content %}
<div id="coindestroy" class="container">

	<h3>Confirmation of coin destroy</h3>

	<p>Do you want to convert <b>{{ num_of_coins }}</b> coins back into money?</p>

	<a href="{% url 'bank:coindestroysuccess' num_of_coins coinpk %}"><button type="button" class="btn btn-primary btn-large btn-block">YES</button></a> 

</div>
{% endblock %}

websites_bank/bank/templates/bank/coindestroysuccess.html
<h1>Bank</h1>

{{ num_of_coins }} coins converted back into money successfully<br>

websites_bank/bank/templates/bank/homepage.html
{% extends 'bank/base.html' %}
{% block content %}
<div id="homepage">    

	<h2>Homepage</h2>

	<h3>Hi {{ user.first_name }} {{ user.last_name }}</h3>

	<?-- http://stackoverflow.com/questions/26282845/userprofileuser-id-2-returns-userprofile-user-but-userprofileuser-id-2-b?>

	<p>Your balance is <b>£{{ request.user.profile.balance }}</b>.</p>

</div>
{% endblock %}

websites_bank/bank/templates/bank/login.html
{% extends 'bank/base.html' %}
{% block content %}
<div id="login" class="container">
	<div class="well well-small">

		<h2>Log in</h2>

		<div id="error_message">
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		</div>

		{% if next %}
		<form action="/bank/login/?next={{next}}" method="post" >
		{%else%}
		<form action="{% url 'bank:login' %}" id="login_form" method="post">
		{% endif %}

		    {% csrf_token %}
		    <div class="form-group">
                <div class="input-group">
				    <div class="input-group-addon"><i class="glyphicon glyphicon-user"></i></div>
				    <input type="text" name="username" class="form-control" placeholder="username" required="required"  value="" size="50">
			    </div>
			    <div class="input-group">
			    	<div class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></div>
			    	<input type="password" class="form-control" name="password" placeholder="password" required="required" value="" size="50">
			    </div>
			</div>
		    <div class="form-group">
		    	<input type="submit" class="btn btn-primary btn-large btn-block" value="Log in" />
		    </div>
		</form>

		<a href="{% url 'bank:register' %}">Register Here</a>

	</div>
</div>
{% endblock %}

websites_bank/bank/templates/bank/register.html
{% extends 'bank/base.html' %}
{% block content %}
<div id="register" class="container">
	<div class="well well-small">

	<h2>Sign up</h2>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	{% load bootstrap3 %}

	<form action="{% url 'bank:register' %}" method="post">
	{% csrf_token %}
	  
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Create Account
            </button>
		{% endbuttons %}
	</form>

	</div>
</div>
{% endblock %}