websites_merchant/merchant/urls.py
from django.conf.urls import url

from . import views

app_name = 'merchant'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'homepage/$', views.homepage, name='homepage'),
    url(r'^(?P<item_id>[0-9]+)/$', views.itemdetail, name='itemdetail'),
    url(r'^(?P<item_id>[0-9]+)/buy/$', views.itembuying, name='itembuying'),
    url(r'success/$', views.itemsuccess, name='itemsuccess'),
    url(r'success2/(?P<item_id>[0-9]+)/$', views.itemsuccess2, name='itemsuccess2'),
]

websites_merchant/websites_merchant/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^merchant/', include('merchant.urls')),
    url(r'^merchant/admin/', admin.site.urls),
]

websites_merchant/merchant/models.py
from __future__ import unicode_literals

from django.db import models

# https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey
# http://stackoverflow.com/questions/12610337/many-to-many-relation-orm-django
# https://docs.djangoproject.com/en/1.9/topics/db/examples/many_to_many/
class Category(models.Model):
	tag = models.CharField(max_length=200)

	def __str__(self):
		return self.tag


# https://coderwall.com/p/bz0sng/simple-django-image-upload-to-model-imagefield
# https://docs.djangoproject.com/en/1.9/intro/tutorial06/
# http://stackoverflow.com/questions/1950069/suspicious-operation-django
class Items(models.Model):
	title = models.CharField(max_length=200)
	description = models.CharField(max_length=600)
	price = models.IntegerField(default=15)
	tags = models.ManyToManyField(Category)
	image = models.ImageField(upload_to='static/merchant/images/', default='static/merchant/images/no-img.jpg')

	def __str__(self):
		return self.title

websites_merchant/merchant/views.py
from django.conf import settings
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import get_object_or_404, render

from merchant.models import Category, Items

import BLcred, blshim

import time, requests

fo = open("timings_merchant.csv", "a", 0)

def index(request):
	return HttpResponseRedirect('/merchant/homepage/?category=')

def homepage(request):
	category = request.GET.get('category')

	if category == "":
		all_items = Items.objects.all()
	else:
		all_items = Items.objects.filter(tags__tag=category)
	
	all_categories = Category.objects.all()
	context = {
		'MERCHANT_URL': settings.MERCHANT_URL,
		'all_items': all_items,
		'all_categories': all_categories
	}
	return render(request, 'merchant/homepage.html', context)


def itemdetail(request, item_id):
	item = get_object_or_404(Items, pk=item_id)
	return render(request, 'merchant/itemdetail.html', {'item': item})


def itembuying(request, item_id):
	item = get_object_or_404(Items, pk=item_id)
	context = {
		'item': item,
		'WALLET_URL': settings.WALLET_URL
		}
	return render(request, 'merchant/itembuying.html', context)


def itemsuccess(request):
	item_id, sessionid = blshim.deserialise(request.GET.get('entry'))

	item = get_object_or_404(Items, pk=item_id)

	im = "merchantbankaccount"
	start = time.time()
	desc = blshim.spending_1(im)
	fo.write("blshim.spending_1, " + str(time.time() - start) + "\n")
	
	serialised_entry = blshim.serialise((desc, sessionid, im))

	start = time.time()
	r = requests.get(settings.WALLET_URL + '/ws_coin_list/?entry=%s' %(serialised_entry))
	fo.write("wallet/ws_coin_list, " + str(time.time() - start) + "\n")
	c = r.content

	valid, error_reason, list_of_msgs = blshim.deserialise(c)

	if valid:
		# want the validation to happen on the bank side because double spending

		# sending all coins to the bank at once
		entry = blshim.serialise((list_of_msgs, desc, im, item.price))

		start = time.time()
		r = requests.get(settings.BANK_URL + '/ws_spend_reveal/?entry=%s' %(entry))
		fo.write("bank/ws_spend_reveal, " + str(time.time() - start) + "\n")
		c = r.content
 
		valid, error_reason = blshim.deserialise(c)

	if valid:
		return render(request, 'merchant/itemsuccess.html', {'item': item})
	else:
		return HttpResponse(error_reason)


def itemsuccess2(request, item_id):
	item = get_object_or_404(Items, pk=item_id)
	return render(request, 'merchant/itemsuccess2.html', {'item': item})

websites_merchant/merchant/templates/merchant/base.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/merchant.css' %}">
    </head>
    <body>

        <div class="page-header">
            <h1><a href="{% url 'merchant:index' %}">Merchant</a></h1>
        </div>
        
        {% block content %}
        {% endblock %}

    </body>
</html>

websites_merchant/merchant/templates/merchant/homepage.html
{% extends 'merchant/base.html' %}
{% block content %}
<div id="index" class="container">

    <div class="categories">
        <h3>Categories:</h3>
        <ul>
        {% for category in all_categories %}
            <li><a href="{{ MERCHANT_URL }}/homepage/?category={{ category }}">{{ category }}</a</li>
        {% endfor %}
    </ul>
    </div>
    <div class="all-items">
        {% if all_items %}
            
            {% for item in all_items %}
                
            <table>
            	<tr>
            		<td rowspan="4" width="140"><img src="/{{ item.image.url }}" align="center" width="120" alt="itempic"></td>
            		<td><h3><a href="{% url 'merchant:itemdetail' item.id %}">{{ item.title }}</a></h3></td>
            	</tr>
            	<tr>
            		<td>{{ item.description }}</td>
            	</tr>
            	<tr>
            		<td><b>Price in coins:</b> {{ item.price }}</td>
            	</tr>
            	<tr>
            		<td><i>
            			{% for t in item.tags.all %}
            				{{ t }},
            			{% endfor %}
            		</i></td>
            	</tr>
            </table>
            <br>

            {% endfor %}
            
        {% else %}
            <p>No items are available.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

websites_merchant/merchant/templates/merchant/itembuying.html
{% extends 'merchant/base.html' %}
{% block content %}
<div id="itembuying">

    <h2>Buying page</h2>

    <p>Order total: <b>{{ item.price }} coins</b></p>

    <button class="btn btn-danger btn-large" onclick="myFunction()">Pay</button>
    <button class="btn btn-danger btn-large" onclick="Remove()">Remove</button>
    <br><br>
    <div id="div1">

    </div>
    <p id="demo"></p>

    <script>
    function myFunction() {
        var x = document.createElement("IFRAME");
        x.setAttribute("src", "{{ WALLET_URL }}/{{ item.price }}/{{ item.id }}");
        x.setAttribute("id", "myFrame");
        x.setAttribute("width", "800");
        x.setAttribute("height", "500");
        var d = document.getElementById("div1");
        //document.body.appendChild(x);
        d.appendChild(x);
    }

    // <button class="btn btn-danger btn-large" onclick="Display()">Display</button>
    function Display() {
        var x = document.getElementById("myFrame").src;
        document.getElementById("demo").innerHTML = x;
    }

    function Remove() {
        var parent = document.getElementById("div1");
        var child = document.getElementById("myFrame");
        parent.removeChild(child);
    }

    </script>

</div>
{% endblock %}

websites_merchant/merchant/templates/merchant/itemdetail.html
{% extends 'merchant/base.html' %}
{% block content %}
<div id="itemdetail">

	<h2>Item page</h2>

	<table>
		<tr>
			<td colspan="2"><h3>{{ item.title }}</h3></td>
		</tr>
		<tr>
			<td rowspan="3"><img src="/{{ item.image.url }}" alt="itempic"></td>
			<td><b>Price in coins:</b> {{ item.price }}</td>
		</tr>
		<tr>
			<td><a href="{% url 'merchant:itembuying' item.id %}"><button class="btn btn-danger btn-large" type="button">BUY</button></a></td>
		</tr>
		<tr>
			<td rowspan="2">{{ item.description }}</td>
		</tr>
		<tr>
			<td><i>
				{% for t in item.tags.all %}
					{{ t }},
				{% endfor %}
			</i></td>
		</tr>
	</table>

</div>
{% endblock %}

websites_merchant/merchant/templates/merchant/itemsuccess.html
<script>
	if (top.location!= self.location) {
	   top.location = "{% url 'merchant:itemsuccess2' item.id %}";
	}
</script>

websites_merchant/merchant/templates/merchant/itemsuccess2.html
{% extends 'merchant/base.html' %}
{% block content %}
<div id="itemsuccess2">


	<h2>{{ item.title }} has been successfully bought !!</h2>

	<br><button class="btn btn-danger btn-large" type="button">Download item</button>

</div>
{% endblock %}